[package]
name = "pl_so"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polars = "0.21.1"
polars-lazy = "0.21.1"
